### ISSUE TITLE
No JavaScript runtime but execjs requires one

### ISSUE THREAD

**Issue by SGraef** [skaes/logjam-docker#2]
When try to start the lates version of the Docker Image:
```
logjam-app         | rake aborted!
logjam-app         | ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
logjam-app         | /opt/logjam/app/vendor/bundle/ruby/3.1.0/gems/execjs-2.8.1/lib/execjs/runtimes.rb:58:in `autodetect'
logjam-app         | /opt/logjam/app/vendor/bundle/ruby/3.1.0/gems/execjs-2.8.1/lib/execjs.rb:5:in `<module:ExecJS>'
logjam-app         | /opt/logjam/app/vendor/bundle/ruby/3.1.0/gems/execjs-2.8.1/lib/execjs.rb:4:in `<top (required)>'
logjam-app         | /opt/logjam/app/vendor/bundle/ruby/3.1.0/gems/terser-1.1.8/lib/terser.rb:6:in `require'
logjam-app         | /opt/logjam/app/vendor/bundle/ruby/3.1.0/gems/terser-1.1.8/lib/terser.rb:6:in `<top (required)>'
logjam-app         | /opt/logjam/app/config/application.rb:24:in `<top (required)>'
logjam-app         | /opt/logjam/app/Rakefile:4:in `require_relative'
logjam-app         | /opt/logjam/app/Rakefile:4:in `<top (required)>'
logjam-app         | /opt/logjam/app/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
logjam-app         | /opt/logjam/bin/bundle:25:in `load'
logjam-app         | /opt/logjam/bin/bundle:25:in `<main>'
logjam-app         | (See full trace by running task with --trace)
```

**Comment by skaes** [comment]
fixed

**Comment by skaes** [comment]
and thx for the report!
